---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: InHello
  labels:
    app: InHello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: InHello
  template:
    metadata:
      labels:
        app: InHello
    spec:
      containers:
        - name: InHello
          image: username/InHello:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: OutHello
  labels:
    app: OutHello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: OutHello
  template:
    metadata:
      labels:
        app: OutHello
    spec:
      containers:
        - name: OutHello
          image: username/OutHello:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: InHello
  labels:
    app: InHello
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: InHello


---


apiVersion: v1
kind: Service
metadata:
  name: OutHello
  labels:
    app: OutHello
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: OutHello

